apiVersion: apps/v1
kind: Deployment
metadata:
  name: will-playground
  namespace: dev
  labels:
    app: will-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: will-playground
  template:
    metadata:
      labels:
        app: will-playground
    spec:
      containers:
        - name: playground
          image: "wil42/playground:v1"
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: will-service
  namespace: dev
spec:
  selector:
    app: will-playground
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: LoadBalancer

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: will-playground
#   namespace: dev
#   labels:
#     app: will-playground
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: wil-playground
#   template:
#     metadata:
#       labels:
#         app: wil-playground
#     spec:
#       serviceAccountName: wil-service
#       containers:
#         - name: wil-playground
#           image: wil42/playground:v1
#           ports:
#           - containerPort: 8888

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: wil-service
#   namespace: dev
# spec:
#   type: NodePort
#   selector:
#     app: wil-playground
#   ports:
#     nodePort: 30080 # 30000-32767
#     port: 8888
#     targetPort: 8888
#     protocol: TCP

# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: wil-service
#   namespace: dev

# ---
# kind: Role
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#   namespace: dev
#   name: wil-role
# rules:
# - apiGroups: [""]
#   resources: ["pods"]
#   verbs: ["get", "watch", "list"]

# ---
# kind: RoleBinding
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#   name: wil-role-binding
#   namespace: dev
# subjects:
# - kind: ServiceAccount
#   name: wil-service
#   namespace: dev
# roleRef:
#   kind: Role
#   name: wil-role
#   apiGroup: rbac.authorization.k8s.io

